---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: weather-app-deployment
  namespace: cst8918
  labels:
    app: weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app
  # This is the pod template
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: weather-app-container
        # this is the Docker image that you created
        image: rlmckenney/cst8918-a01-weather-app:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          # this directive does not work with docker-desktop nodes
          # runAsNonRoot: true
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
        ports:
        - containerPort: 8080
        env:
          - name: WEATHER_API_KEY
            valueFrom:
              secretKeyRef:
                name: weather
                key: api-key
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP